MTEngine:
    MTengine: Marian
    #one of Marian, OpenNMT, Moses, GoogleTranslate, DeepL, Lucy
    startMTEngine: True
    startCommand: "./marian-server-CPU -m model.bin -v vocab-es.yml vocab-pt.yml -p 8261 --n-best  --alignment hard  --normalize 1 --quiet &"
    IP: localhost
    port: 8261
    min_len_factor: 0.5
    
MTUOCServer:
  port: 8011
  type: MTUOC
  #one of MTUOC, Moses, ModernMT, OpenNMT, NMTWizard
  verbosity_level: 3
  
  checkistranslatable: True
  restore_tags: True
  fix_xml: True
  
  URLs: True
  code_URLs: "@URL@"
  EMAILs: True
  code_EMAILs: "@EMAIL@"
  
  replaceNUMs: True
  
  splitNUMs: False
  
  min_chars_segment: 2  
  translation_selection_strategy: First
  log_file: log.log
  ONMT_url_root: "/translator"
  
SRX_file: segment.srx


Preprocess:
  sl_lang: es
  tl_lang: pt
  tokenize_SL: True
  sl_tokenizer: MTUOC_tokenizer_spa.py
  #one of the MTUOC-tokenizers or state Moses if you use Moses tokenizers
  tl_tokenizer: MTUOC_tokenizer_por.py
  #one of the MTUOC-tokenizers or state Moses if you use Moses tokenizers
  
  segment_input: True
  SRXfile: segmentSC.srx
  SRXlang: Spanish
  
  replaceNUMs: True
  code_NUMs: "@NUM@"
  splitNUMs: False
  #Truecasing
  tcmodel: tc.es
  #or None if not used
  truecase: all
  #one of None, all, upper
  ###SentencePiece###
  sentencepiece: False
  sp_model_SL: spmodel.model
  sp_model_TL: spmodel.model
  sp_splitter: "‚ñÅ"
  
  #BPE
  BPE: True
  #True or False: if sentencepiece is set to True, sentencepiece will be used
  bpecodes: codes_file
  bpe_joiner: "@@"
  
  bos_annotate: True
  bos_symbol: <s>
  #None or <s> (or other)
  eos_annotate: True
  eos_symbol: </s>

#hmtl entities

unescape_html_input: True
escape_html_input: False

unescape_html_output: True
escape_html_output: False 

change_input_files: None
change_output_files: None
change_translation_files: None
  
GoogleTranslate:
  sllang: en
  tllang: es
  glossary: None
  #state None if no glossary is used, otherwise the name of the glossary
  project_id: XXxxXXXXX
  location: us-central1
  jsonfile: XXxxXXXXX.json
  
DeepL:
  API_key: XXxxXXXXX
  sllang: EN
  tllang: ES
  #tag_handling: html
  #one of html, xml
  formality: default
  #one of default, less, more
  split_sentences: "off"
  #one of "off", "on", "nonewlines"
  glossary: None
  
Lucy:
  url: http://XXX.XXX.XXX:8080/AutoTranslateRS/V1.3/mtrans/exec/
  TRANSLATION_DIRECTION: SPANISH-CATALAN
  MARK_UNKNOWNS: 0
  MARK_ALTERNATIVES: 0
  MARK_COMPOUNDS: 0
  CHARSET: UTF
