MTEngine:
    MTengine: Marian
    #one of Marian, OpenNMT, Moses
    startMTEngine: True
    #startCommand: "./marian-server -m model.npz -v vocab-en.yml vocab-es.yml -p 8085 --n-best --alignment hard  --normalize 1 --quiet &"
    startCommand: "./marian-server-CPU -m model.bin -v vocab-en.yml vocab-es.yml -p 8050 --n-best --alignment hard  --normalize 1 --quiet &"
    #startCommand: "./marian-server-GPU --models model.bin model.bin.best-cross-entropy.bin model.bin model.bin.best-bleu-detok.bin --weights 0.4 0.3 0.3 --vocabs vocab-es.yml vocab-ca.yml -p 8090 --n-best --alignment hard  --normalize 1 --quiet &"
    #startCommand: "onmt_server --ip localhost --port 8085 --url_root /translator --config config.json"
    #startCommand: "./moses -f moses.ini --server --server-port 8085 --print-alignment-info&"
    #add --quiet if you don't want to see log from Marian
    IP: localhost
    port: 8050
    #The port is needed for MTUOC-stop-server.py
    min_len_factor: 0.5
    #for Marian to avoid very short translations
    
MTUOCServer:
  port: 8005
  type: MTUOC
  #one of MTUOC, Moses, ModernMT, OpenNMT, NMTWizard
  verbosity_level: 0
  #level 1: start, stop, errors; level 2: level 1 and source and translated segments; level 3: levels 1 and 2 and details on translation
  log_file: log.log
  #log file path and name or None
  #0: no verbosity; higher more detailed
  restore_tags: True
  fix_xml: True
  strictTagRestoration: True
  #if true, verifies that all tags are in the target, otherwise returns translation without tags
  restore_case: True
  URLs: True
  code_URLs: "@URL@"
  EMAILs: True
  code_EMAILs: "@EMAIL@"
  replaceNUMs: False
  code_NUMs: "@NUM@"
  splitNUMs: False
  add_trailing_space: True
  unescape_html: True
  min_chars_segment: 2
  max_chars_segment: 300
  checkistranslatable: True
  on_error: errorsource
  #one of: source errormessage errorsource
  segment_splitters: 
    - ";"
    - ":"
    - ","
    - and
    - or
  ONMT_url_root: "/translator"
  #specific configuration when acting as ONMT server
  
Preprocess:
  sl_lang: en
  tl_lang: es
  tokenize_SL: False
  sl_tokenizer: MTUOC_tokenizer_eng.py
  tl_tokenizer: MTUOC_tokenizer_spa.py
  #Truecasing
  tcmodel: tc.en
  #or None if not used
  truecase: upper
  #one of None, all, upper
  ###SentencePiece###
  sentencepiece: True
  sp_model_SL: spmodel.model
  sp_model_TL: spmodel.model
  sp_splitter: "‚ñÅ"
  
  #BPE subword-nmt
  BPE: False
  #True or False: if sentencepiece is set to True, sentencepiece will be used
  bpecodes: codes_file
  bpe_joiner: "@@"

  
  #or None if not used
  ###################
  bos_annotate: True
  bos_symbol: <s>
  #None or <s> (or other)
  eos_annotate: True
  eos_symbol: </s>
  #None or </s> (or other)

  finaldetokenization: True
  #one of True False

#hmtl entities

unescape_html_input: True
escape_html_input: False

unescape_html_output: True
escape_html_output: False

change_input_files: None
change_output_files: None
change_translation_files: None
# None or list of files separated by ; error_correction.txt;translated_names.txt

USER_DEFINED_SYMBOLS: <tag0> <tag1> <tag2> <tag3> <tag4> <tag5> <tag6> <tag7> <tag8> <tag9> <tag10> </tag0> </tag1> </tag2> </tag3> </tag4> </tag5> </tag6> </tag7> </tag8> </tag9> </tag10> <tag0/> <tag1/> <tag2/> <tag3/> <tag4/> <tag5/> <tag6/> <tag7/> <tag8/> <tag9/> <tag10/>

#GoogleTranslate configuration

GoogleTranslate:
  sllang: en
  tllang: es
  glossary: None
  #state None if no glossary is used, otherwise the name of the glossary
  project_id: XXXXXXXXXX
  location: us-central1
  jsonfile: XXXXXXXXXX
  
#DeepL configuration
DeepL:
  API_key: XXXXXXXXXX
  sllang: EN
  tllang: ES
  #tag_handling: html
  #one of html, xml
  formality: default
  #one of default, less, more
  split_sentences: "off"
  #one of "off", "on", "nonewlines"
  glossary: None
  
#Lucy configuration
Lucy:
  url: http://XXXXXXXXXX:8080/AutoTranslateRS/V1.3/mtrans/exec/
  TRANSLATION_DIRECTION: SPANISH-CATALAN
  MARK_UNKNOWNS: 0
  MARK_ALTERNATIVES: 0
  MARK_COMPOUNDS: 0
  CHARSET: UTF
  
